### ISSUE TITLE
404 when downloading models

### ISSUE THREAD

**Issue by bodonkerhoderos** [purgeme/MediapipeModule_library#1]
based on [this page](https://google.github.io/mediapipe/solutions/models.html#mediapipe-models-and-model-cards) it looks like they have moved the tflite files to storage.googleapis.com/mediapipe-assets/

after doing a simple find and replace i on build.sh i was able to get it to download all the files and build

(note the txt files are still available on github)

(also thanks for this)

**Comment by purgeme** [comment]
You mean the download_models.sh file right ?

**Comment by purgeme** [comment]
I have fixed the urls
